spring:
  profiles: prod
  mvc:
    view:
      prefix: /user/
      suffix: .html
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://47.422.322.103:3306/coupon?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
#      password: root
      password: xxxxxxxx
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 0
    #    host: 121.201.43.229
    host: 127.0.0.1
    port: 6379
    #    password: huazhongBAO
    password:
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
    timeout: 20000


logging:
  level:
    com.superman.superman: debug
  file: ./logs/core.log
  root: INFO


server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.superman.superman.model

juanhuang:
  range: 90
  look: "score_look"
  sign: "score_sign"
  invscore: 20

domain:
  url: "http://1232320.79.62.89/"
  codeurl: "http://www.dd.com"
  localurl: "http://192.168.0.102"
  jdimageurl: "http://img14.360buyimg.com/n1/"
  jdUrl: "https://router.jd.com/api"
  jdsecret: "b4089a6f60e148318071f26a5805f6e1"
  jdkey: "bdead8780fda4a068b83f3f7874f311e"
  jduid: "1001347399"
  qnyurl: "http://qny.ds.com/"

pdd_pro:
  pdd-key: "8f8a9efa079b4fb8a2d9fa86352b5e00"
  pdd-secret: "36f5e05bfcce59ec6a0d6f27f380362c831239d7"
  pdd-access_token: "fd5d312adc6e4200bcf314cf943a287593ee3f07"
  pdd-url: "http://quanhuangmaoyi.com"
  pdd-router-url: "https://gw-api.pinduoduo.com/api/router"
tb:
  appkey: "25645650"
  secret: "8a9d6928c954bbf4052d2a2c8841f754"
  adzoneid: "328000440"
  api-url: "http://gw.api.taobao.com/router/rest"
  pid: 92706150203

miao:
  apkey: "c003483d-fd72-c78a-72ec-1d0e6034919d"
  tbname: "sd"
  url:  "https://api.open.21ds.cn/apiv1/"
  openurl:  "https://api.open.21ds.cn/op_api_v1/"

weixin:
  wx-key: "bbc1737d63e44e278dbffa9e96a7eca3"
  wx-secret: "5e1a03eb561bac0c63c5efc8c1472119fc3ad405"
  wx-access_token: "fd5d312adc6e4200bcf314cf943a287593ee3f07"

